version: "3.0"

services:
  web:
    build:
      dockerfile: ./.docker/web/Dockerfile
      context: .
    ports:
      - "8080:80"
    environment:
      PORT: 80
      NODE_ENVIROMENT: ${NODE_ENVIROMENT}
      SENTRY_ENVIROMENT: ${NODE_ENVIROMENT}
      NODE_AUTH_TOKEN_JWT: ${NODE_AUTH_TOKEN_JWT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URI: ${DB_URI}
      DB_NAME: ${DB_NAME}
      NOTIFICATIONS_TOKEN: ${NOTIFICATIONS_TOKEN}
      LOGGER_USER: ${LOGGER_USER}
      LOGGER_PASS: ${LOGGER_PASS}
      BLIP_SIGNATURE: ${BLIP_SIGNATURE}
    networks:
      default:
        aliases:
          - api
  
  nginx: 
    build:
      dockerfile: ./.docker/nginx/Dockerfile
      context: .
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/trusted_ips.conf:/etc/nginx/trusted_ips.conf
    depends_on:
      - web
    networks:
      - default


networks:
   default: