version: "3.0"

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      PORT: 80
      NODE_ENVIROMENT: production
      SENTRY_ENVIROMENT: production
      NODE_AUTH_TOKEN_JWT: ${NODE_AUTH_TOKEN_JWT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_URI: ${DB_URI}
      NOTIFICATIONS_TOKEN: ${NOTIFICATIONS_TOKEN}
      LOGGER_USER: ${LOGGER_USER}
      LOGGER_PASS: ${LOGGER_PASS}
      BLIP_SIGNATURE: ${BLIP_SIGNATURE}