name: Deploy on AWS EC2

on:
  push:
    branches: 
      - staging

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: AWS SSM Send Command
      uses: peterkimzz/aws-ssm-send-command@master
      id: ssm
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        instance-ids: ${{ secrets.INSTANCE_ID }}
        comment: Send command to deploy main branch
        working-directory: /home/ubuntu/api
        command: /bin/sh ./deploy.sh
